### ISSUE TITLE
Exception after Upgrading from SQ 5.5 to 6.1

### ISSUE THREAD

**Issue by philipooo** [Pablissimo/SonarTsPlugin#63]
Today we upgraded from SonarQube 5.5 to 6.1. We also updated the plugin to 0.93-SNAPSHOT.

The runner:

```
INFO: SonarQube Scanner 2.8
INFO: Java 1.8.0_111 Oracle Corporation (64-bit)
```

The error:

```
error	26-Oct-2016 15:17:17	Exception in thread "main" java.lang.NoSuchMethodError: org.sonar.api.resources.File.fromIOFile(Ljava/io/File;Lorg/sonar/api/resources/Project;)Lorg/sonar/api/resources/File;
error	26-Oct-2016 15:17:17		at com.pablissimo.sonar.TsLintSensor.getFileFromIOFile(TsLintSensor.java:177)
error	26-Oct-2016 15:17:17		at com.pablissimo.sonar.TsLintSensor.analyse(TsLintSensor.java:152)
error	26-Oct-2016 15:17:17		at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
error	26-Oct-2016 15:17:17		at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
error	26-Oct-2016 15:17:17		at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
error	26-Oct-2016 15:17:17		at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
error	26-Oct-2016 15:17:17		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
error	26-Oct-2016 15:17:17		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
error	26-Oct-2016 15:17:17		at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
error	26-Oct-2016 15:17:17		at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
error	26-Oct-2016 15:17:17		at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
error	26-Oct-2016 15:17:17		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
error	26-Oct-2016 15:17:17		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
error	26-Oct-2016 15:17:17		at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
error	26-Oct-2016 15:17:17		at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
error	26-Oct-2016 15:17:17		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
error	26-Oct-2016 15:17:17		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
error	26-Oct-2016 15:17:17		at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
error	26-Oct-2016 15:17:17		at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
error	26-Oct-2016 15:17:17		at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
error	26-Oct-2016 15:17:17		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
error	26-Oct-2016 15:17:17		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
error	26-Oct-2016 15:17:17		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
error	26-Oct-2016 15:17:17		at java.lang.reflect.Method.invoke(Unknown Source)
error	26-Oct-2016 15:17:17		at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
error	26-Oct-2016 15:17:17		at com.sun.proxy.$Proxy0.execute(Unknown Source)
error	26-Oct-2016 15:17:17		at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
error	26-Oct-2016 15:17:17		at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
error	26-Oct-2016 15:17:17		at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
error	26-Oct-2016 15:17:17		at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
error	26-Oct-2016 15:17:17		at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

Let me know if you need some additional informations.
Thank you for providing thins plugin!

**Comment by Pablissimo** [comment]
Hmm, that's new! Did you copy the new version of the plugin into place before or after upgrading, i.e. did you bounce SonarQube between copying the new version and running analysis?

I ask only because v0.93 doesn't have a method called analyse any more on TsLintSensor which suggests something's cached somewhere?

(See https://github.com/Pablissimo/SonarTsPlugin/blob/sq6support/src/main/java/com/pablissimo/sonar/TsLintSensor.java)

Also: thanks for helping out on #61 :)

**Comment by philipooo** [comment]
Hi @Pablissimo 

Thanks for having a look at it. Your totally right... the stacktrace was of a run using the 0.9-SNAPSHOT. Maybe I made something wrong copy an pasting it to github. Sorry for the confusion ;) The last analysis definitely uses the 0.93-SNAPSHOT and gives me the following error:

```
build	26-Oct-2016 16:08:07	16:08:07.799 DEBUG:   * TypeScript 0.93-SNAPSHOT (typescript)
...
error	26-Oct-2016 16:08:26	Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Objects
error	26-Oct-2016 16:08:26		at com.pablissimo.sonar.LCOVParserImpl$FileData.addBranch(LCOVParserImpl.java:200)
error	26-Oct-2016 16:08:26		at com.pablissimo.sonar.LCOVParserImpl.parse(LCOVParserImpl.java:126)
error	26-Oct-2016 16:08:26		at com.pablissimo.sonar.LCOVParserImpl.<init>(LCOVParserImpl.java:60)
error	26-Oct-2016 16:08:26		at com.pablissimo.sonar.LCOVParserImpl.create(LCOVParserImpl.java:73)
error	26-Oct-2016 16:08:26		at com.pablissimo.sonar.TsCoverageSensorImpl.getParser(TsCoverageSensorImpl.java:106)
error	26-Oct-2016 16:08:26		at com.pablissimo.sonar.TsCoverageSensorImpl.saveMeasureFromLCOVFile(TsCoverageSensorImpl.java:81)
error	26-Oct-2016 16:08:26		at com.pablissimo.sonar.TsCoverageSensorImpl.execute(TsCoverageSensorImpl.java:141)
error	26-Oct-2016 16:08:26		at com.pablissimo.sonar.CombinedCoverageSensor.execute(CombinedCoverageSensor.java:34)
error	26-Oct-2016 16:08:26		at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
error	26-Oct-2016 16:08:26		at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
error	26-Oct-2016 16:08:26		at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
error	26-Oct-2016 16:08:26		at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
error	26-Oct-2016 16:08:26		at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
error	26-Oct-2016 16:08:26		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
error	26-Oct-2016 16:08:26		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
error	26-Oct-2016 16:08:26		at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
error	26-Oct-2016 16:08:26		at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
error	26-Oct-2016 16:08:26		at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
error	26-Oct-2016 16:08:26		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
error	26-Oct-2016 16:08:26		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
error	26-Oct-2016 16:08:26		at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
error	26-Oct-2016 16:08:26		at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
error	26-Oct-2016 16:08:26		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
error	26-Oct-2016 16:08:26		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
error	26-Oct-2016 16:08:26		at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
error	26-Oct-2016 16:08:26		at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
error	26-Oct-2016 16:08:26		at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
error	26-Oct-2016 16:08:26		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
error	26-Oct-2016 16:08:26		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
error	26-Oct-2016 16:08:26		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
error	26-Oct-2016 16:08:26		at java.lang.reflect.Method.invoke(Unknown Source)
error	26-Oct-2016 16:08:26		at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
error	26-Oct-2016 16:08:26		at com.sun.proxy.$Proxy0.execute(Unknown Source)
error	26-Oct-2016 16:08:26		at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
error	26-Oct-2016 16:08:26		at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
error	26-Oct-2016 16:08:26		at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
error	26-Oct-2016 16:08:26		at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
error	26-Oct-2016 16:08:26		at org.sonarsource.scanner.cli.Main.main(Main.java:61)
error	26-Oct-2016 16:08:26	Caused by: java.lang.ClassNotFoundException: com.google.common.base.Objects
error	26-Oct-2016 16:08:26		at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
error	26-Oct-2016 16:08:26		at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
error	26-Oct-2016 16:08:26		at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
error	26-Oct-2016 16:08:26		... 38 more
```

Seems to be the same issue as in  #58 

Here are some additional informations about the run:

```
build	26-Oct-2016 16:08:05	16:08:05.345 INFO: SonarQube Scanner 2.8
build	26-Oct-2016 16:08:05	16:08:05.345 INFO: Java 1.8.0_111 Oracle Corporation (64-bit)
build	26-Oct-2016 16:08:05	16:08:05.345 INFO: Windows 8.1 6.3 amd64
```

As I understand #58 there is currently no workaround when using 6.1, right?

**Comment by Pablissimo** [comment]
Not at present; there are a couple of pull requests that deal with the issue, so you could have a bash at building one of those. However, finally thing I can reproduce it now so hopefully I can either do that shortly or work out a 5.6-compatible fix.

**Comment by philipooo** [comment]
Okay. I dont have the build environment to build java stuff, but is it possible to download the artifacts out of travis-ci? May you want to close this issue in favor of #58. Thanks for your effort!

**Comment by Pablissimo** [comment]
I'll leave it open for now, might spur me on to actually get it fixed! Think I have to configure Travis to upload artifacts to something like S3 for things like pull requests so there probably isn't a quick way of getting the binaries out short of building.

**Comment by Pablissimo** [comment]
Fixed with v0.94, now released.
